version: '3'

services:
  odoo-middleware:
    image: odoo-middleware
    container_name: odoo-middleware
    user: odoo-user
    ports: 
    - "5000:5000"
    environment:
    - ODOO_LOGIN=
    - ODOO_PASSWORD=
    - ODOO_DB=
    - ODOO_HOST=
    - ODOO_PORT=
    - ODOO_SECRET=
    entrypoint: ./boot.sh
    
