version: '3'

services:
  odoo-middleware:
    image: odoo-middleware
    container_name: odoo-middleware
    user: odoo-user
    ports: 
    - "5000:5000"
    environment:
    - LOGIN=
    - PASSWORD=
    - DB=
    - HOST=
    - PORT=
    - SECRET=
    entrypoint: ./boot.sh
    